# Generated by Django 4.2.5 on 2023-10-04 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('NumberOfRooms', models.IntegerField(blank=True, null=True, verbose_name='تعداد اتاق خواب')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='طبقه')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='متراژ')),
                ('have_Warehouse', models.BooleanField(blank=True, null=True, verbose_name='آیا انباری دارد ؟')),
                ('have_parking', models.BooleanField(blank=True, null=True, verbose_name='آیا پارکینگ دارد ؟')),
                ('have_balcony', models.BooleanField(blank=True, null=True, verbose_name='آیا بالکن دارد ؟')),
                ('PricePerMeter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت هر متر')),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت کل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس در نقشه')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ و زمان ایجاد آگهی')),
                ('priority', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='apartments', verbose_name='عکس ۱')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='apartments', verbose_name='عکس ۲')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='apartments', verbose_name='عکس ۳')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='apartments', verbose_name='عکس ۴')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='apartments', verbose_name='عکس ۵')),
                ('pic6', models.ImageField(blank=True, null=True, upload_to='apartments', verbose_name='عکس ۶')),
            ],
            options={
                'verbose_name': 'آگهی آپارتمان',
                'verbose_name_plural': 'آگهی آپارتمان ها',
                'db_table': 'Apartment',
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='متراژ زمین')),
                ('PricePerMeter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت هر متر')),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت کل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس در نقشه')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ و زمان ایجاد آگهی')),
                ('priority', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='lands', verbose_name='عکس ۱')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='lands', verbose_name='عکس ۲')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='lands', verbose_name='عکس ۳')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='lands', verbose_name='عکس ۴')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='lands', verbose_name='عکس ۵')),
                ('pic6', models.ImageField(blank=True, null=True, upload_to='lands', verbose_name='عکس ۶')),
            ],
            options={
                'verbose_name': 'آگهی زمین',
                'verbose_name_plural': 'آگهی زمین ها',
                'db_table': 'Land',
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('landSize', models.IntegerField(blank=True, null=True, verbose_name='متراژ زمین')),
                ('buildingSize', models.IntegerField(blank=True, null=True, verbose_name='متراژ بنا')),
                ('NumberOfRooms', models.IntegerField(blank=True, null=True, verbose_name='تعداد اتاق خواب')),
                ('PricePerMeter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت هر متر')),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت کل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس در نقشه')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ و زمان ایجاد آگهی')),
                ('priority', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='villas', verbose_name='عکس ۱')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='villas', verbose_name='عکس ۲')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='villas', verbose_name='عکس ۳')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='villas', verbose_name='عکس ۴')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='villas', verbose_name='عکس ۵')),
                ('pic6', models.ImageField(blank=True, null=True, upload_to='villas', verbose_name='عکس ۶')),
            ],
            options={
                'verbose_name': 'آگهی ویلا',
                'verbose_name_plural': 'آگهی ویلا ها',
                'db_table': 'Villa',
            },
        ),
    ]
