# Generated by Django 4.2.6 on 2023-10-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی\u200c ها',
                'db_table': 'Category',
            },
        ),
        migrations.AlterField(
            model_name='apartment',
            name='PricePerMeter',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت هر متر'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='totalPrice',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='land',
            name='PricePerMeter',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت هر متر'),
        ),
        migrations.AlterField(
            model_name='land',
            name='totalPrice',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='PricePerMeter',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت هر متر'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='totalPrice',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AddField(
            model_name='land',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ads.category', verbose_name='دسته بندی'),
        ),
    ]
