# Generated by Django 4.2.6 on 2023-10-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0005_rename_category_category_en_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='db_name',
            field=models.CharField(default='زمین', editable=False, max_length=20, verbose_name='نام جدول'),
        ),
        migrations.AddField(
            model_name='land',
            name='db_name',
            field=models.CharField(default='زمین', editable=False, max_length=20, verbose_name='نام جدول'),
        ),
        migrations.AddField(
            model_name='villa',
            name='db_name',
            field=models.CharField(default='زمین', editable=False, max_length=20, verbose_name='نام جدول'),
        ),
        migrations.AlterField(
            model_name='category',
            name='en_category',
            field=models.CharField(max_length=20, verbose_name='نوع آگهی (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='fa_category',
            field=models.CharField(max_length=20, verbose_name='نوع آگهی (فارسی)'),
        ),
    ]
