# Generated by Django 4.2.6 on 2023-10-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0006_apartment_db_name_land_db_name_villa_db_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='land',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='db_name',
        ),
        migrations.AddField(
            model_name='apartment',
            name='en_db_name',
            field=models.CharField(default='Apartment', editable=False, max_length=20, verbose_name='نام جدول (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='fa_db_name',
            field=models.CharField(default='آپارتمان', editable=False, max_length=20, verbose_name='نام جدول (فارسی)'),
        ),
        migrations.AddField(
            model_name='land',
            name='en_db_name',
            field=models.CharField(default='Land', editable=False, max_length=20, verbose_name='نام جدول (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='land',
            name='fa_db_name',
            field=models.CharField(default='زمین', editable=False, max_length=20, verbose_name='نام جدول (فارسی)'),
        ),
        migrations.AddField(
            model_name='villa',
            name='en_db_name',
            field=models.CharField(default='Villa', editable=False, max_length=20, verbose_name='نام جدول (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='villa',
            name='fa_db_name',
            field=models.CharField(default='ویلا', editable=False, max_length=20, verbose_name='نام جدول (فارسی)'),
        ),
    ]
