# Generated by Django 4.2.7 on 2023-11-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0008_currency_apartment_adaptive_land_adaptive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'واحد پولی', 'verbose_name_plural': 'واحد های پولی'},
        ),
        migrations.AlterModelTable(
            name='currency',
            table='Currency',
        ),
    ]
