# Generated by Django 4.2.7 on 2023-11-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0009_alter_currency_options_alter_currency_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='have_Warehouse',
            field=models.BooleanField(default=False, verbose_name='آیا انباری دارد ؟'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='have_balcony',
            field=models.BooleanField(default=False, verbose_name='آیا بالکن دارد ؟'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='have_parking',
            field=models.BooleanField(default=False, verbose_name='آیا پارکینگ دارد ؟'),
        ),
    ]
