# Generated by Django 4.2.7 on 2023-11-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0010_alter_apartment_have_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='prepayment',
            field=models.IntegerField(blank=True, null=True, verbose_name='پیش پرداخت'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rent',
            field=models.IntegerField(blank=True, null=True, verbose_name='اجاره'),
        ),
        migrations.AddField(
            model_name='land',
            name='prepayment',
            field=models.IntegerField(blank=True, null=True, verbose_name='پیش پرداخت'),
        ),
        migrations.AddField(
            model_name='land',
            name='rent',
            field=models.IntegerField(blank=True, null=True, verbose_name='اجاره'),
        ),
    ]
