# Generated by Django 4.2.7 on 2023-11-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logger',
            options={'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدید ها'},
        ),
    ]
