# Generated by Django 4.2.7 on 2023-11-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AboutUs')),
                ('header_1', models.CharField(max_length=100)),
                ('body_1', models.TextField()),
                ('header_2', models.CharField(max_length=100)),
                ('body_2', models.TextField()),
                ('header_3', models.CharField(max_length=100)),
                ('body_3', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
                'db_table': 'AboutUs',
            },
        ),
    ]
