# Generated by Django 4.2.7 on 2023-11-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContacUs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ContactUs',
        ),
    ]
