# Generated by Django 4.2.7 on 2023-11-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContacUs', '0002_rename_message_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ارسال پیام'),
        ),
    ]
