# Generated by Django 4.2.7 on 2023-11-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseConfig', '0003_alter_footerdata_options_footerdata_landlineـphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerdata',
            old_name='landlineـphone',
            new_name='landline_phone',
        ),
    ]
