# Generated by Django 4.2.7 on 2023-11-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseConfig', '0004_rename_landlineـphone_footerdata_landline_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه اصلی',
                'verbose_name_plural': 'اطلاعات صفحه اصلی',
                'db_table': 'HomeData',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Slider')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'عکس اسلایدر',
                'verbose_name_plural': 'عکس های اسلایدر',
                'db_table': 'SliderImage',
            },
        ),
    ]
