# Generated by Django 4.2.7 on 2023-11-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseConfig', '0005_homedata_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerdata',
            name='per_page_item',
            field=models.IntegerField(default=20),
        ),
    ]
