# Generated by Django 4.2.7 on 2023-11-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseConfig', '0006_footerdata_per_page_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdata',
            name='per_page_item',
            field=models.IntegerField(default=10),
        ),
    ]
