# Generated by Django 4.2.7 on 2023-11-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseConfig', '0007_alter_footerdata_per_page_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerdata',
            options={'verbose_name': 'تنطیمات عمومی سایت', 'verbose_name_plural': 'تنظیمات عمومی سایت'},
        ),
    ]
